// ============================================================
// /lib/meditations.ts — Static meditation data
// REPLACE: swap this array with a CMS fetch via /lib/cms.ts
// when Sanity/Contentful is connected.
// ============================================================

import type { Meditation } from "./types";

// REPLACE: this static array will be replaced by cms.getMeditations()
export const meditations: Meditation[] = [
    {
        id: "1",
        slug: "breath-of-stillness",
        title: "The Watcher Behind the Mind",
        description: "Theme: Discovering the Witness",
        longDescription: "Core: Observing thoughts without suppression\nDepth: Shift from thinker → observer → awareness",
        duration: "18 minutes",
        audioSrc: "/audio/breath-of-stillness.mp3",
        coverImage: "/audio/breath-of-stillness.jpg",
        tier: "free",
        tags: ["witness", "awareness"],
    },
    {
        id: "2",
        slug: "the-inner-witness",
        title: "The Inner Scientist",
        description: "Theme: Meditation as investigation",
        longDescription: "Core: Dispassionate observation\nDepth: Detachment without emotional coldness",
        duration: "20 minutes",
        audioSrc: "/audio/the-inner-witness.mp3",
        coverImage: "/audio/the-inner-witness.jpg",
        tier: "free",
        tags: ["investigation", "observation"],
    },
    {
        id: "3",
        slug: "the-flash-of-the-overself",
        title: "The Flash of the Overself",
        description: "Theme: Recognizing inner illumination",
        longDescription: "Core: Relaxation into sudden clarity\nDepth: Recognizing subtle intuitive presence",
        duration: "22 minutes",
        audioSrc: "/audio/the-flash-of-the-overself.mp3",
        coverImage: "/audio/the-flash-of-the-overself.jpg",
        tier: "free",
        tags: ["illumination", "clarity"],
    },
    {
        id: "4",
        slug: "the-long-path",
        title: "The Long Path — Self-Correction",
        description: "Theme: Refining ego tendencies",
        longDescription: "Core: Observe reaction patterns\nDepth: Silent character purification",
        duration: "24 minutes",
        audioSrc: "/audio/the-long-path.mp3",
        coverImage: "/audio/the-long-path.jpg",
        tier: "premium",
        tags: ["long-path", "refinement"],
    },
    {
        id: "5",
        slug: "the-short-path",
        title: "The Short Path — Immediate Presence",
        description: "Theme: Effortless Being",
        longDescription: "Core: Drop all striving\nDepth: Recognize presence instantly",
        duration: "20 minutes",
        audioSrc: "/audio/the-short-path.mp3",
        coverImage: "/audio/the-short-path.jpg",
        tier: "free",
        tags: ["short-path", "presence"],
    },
    {
        id: "6",
        slug: "silence-without-forcing",
        title: "Silence Without Forcing",
        description: "Theme: Non-violent stillness",
        longDescription: "Core: Letting quiet happen\nDepth: Difference between suppression and silence",
        duration: "23 minutes",
        audioSrc: "/audio/silence-without-forcing.mp3",
        coverImage: "/audio/silence-without-forcing.jpg",
        tier: "premium",
        tags: ["silence", "stillness"],
    },
    {
        id: "7",
        slug: "self-remembering",
        title: "Self-Remembering in Daily Life",
        description: "Theme: Awareness in activity",
        longDescription: "Core: Bring “I Am” into movement\nDepth: Dual attention practice",
        duration: "21 minutes",
        audioSrc: "/audio/self-remembering.mp3",
        coverImage: "/audio/self-remembering.jpg",
        tier: "free",
        tags: ["activity", "awareness"],
    },
    {
        id: "8",
        slug: "heart-of-detachment",
        title: "The Heart of Detachment",
        description: "Theme: Emotional clarity",
        longDescription: "Core: Observe emotion without drowning\nDepth: Stable center during intensity",
        duration: "22 minutes",
        audioSrc: "/audio/heart-of-detachment.mp3",
        coverImage: "/audio/heart-of-detachment.jpg",
        tier: "free",
        tags: ["detachment", "clarity"],
    },
    {
        id: "9",
        slug: "inner-guide",
        title: "The Inner Guide",
        description: "Theme: Intuition vs imagination",
        longDescription: "Core: Feeling the higher impulse\nDepth: Recognizing ego vs Overself signals",
        duration: "23 minutes",
        audioSrc: "/audio/inner-guide.mp3",
        coverImage: "/audio/inner-guide.jpg",
        tier: "premium",
        tags: ["intuition", "guidance"],
    },
    {
        id: "10",
        slug: "descent-into-stillness",
        title: "The Descent into Stillness",
        description: "Theme: Gradual interiorization",
        longDescription: "Core: Relax → subtle breath → subtle mind\nDepth: Enter deep quiet safely",
        duration: "25 minutes",
        audioSrc: "/audio/descent-into-stillness.mp3",
        coverImage: "/audio/descent-into-stillness.jpg",
        tier: "premium",
        tags: ["stillness", "interiorization"],
    },
    {
        id: "11",
        slug: "presence-beyond-identity",
        title: "The Presence Beyond Identity",
        description: "Theme: Beyond roles & personality",
        longDescription: "Core: Drop social self\nDepth: Awareness without label",
        duration: "24 minutes",
        audioSrc: "/audio/presence-beyond-identity.mp3",
        coverImage: "/audio/presence-beyond-identity.jpg",
        tier: "free",
        tags: ["identity", "awareness"],
    },
    {
        id: "12",
        slug: "grace-of-the-overself",
        title: "The Grace of the Overself",
        description: "Theme: Surrender to higher intelligence",
        longDescription: "Core: Effort ends in receptivity\nDepth: Silent communion",
        duration: "20 minutes",
        audioSrc: "/audio/grace-of-the-overself.mp3",
        coverImage: "/audio/grace-of-the-overself.jpg",
        tier: "premium",
        tags: ["grace", "overself"],
    },
];
